baseURL = "http://dphowes.github.io"
title = "D. Howes"
copyright = "2017"

theme = "minimo"

disqusShortname = ""
googleAnalytics = ""
Paginate = 5

preserveTaxonomyNames = true

[params]
  description = ""
  dateFormat = "2006, Jan 2"
  copyrightOwner = "dph"
  copyrightStartYear = "2017"
  favicon = "favicon.png"
  hideEntryNavigation = false
  customCSS = ["css/prism.css"]
  customJS = ["js/prism.js", "js/custom.js"]
  hideSocialMenu = false
  showReadTime = true

[params.seo]
  # Title Separator: - – — · • * ⋆ | ~ « » < >
  titleSeparator = "•"

[params.opengraph]
  [params.opengraph.facebook]
    admins = ""
    appid = ""

[taxonomies]
  category = "categories"
  tag = "tags"

[social]
  facebook = ""

[author]
  name = "dph"

[author.social]
  codepen = ""
  email = "devinhowes@gmail.com"
  facebook = ""
  github = "dphowes"
  instagram = ""
  twitter = ""
  linkedin = "devin-howes/"

[permalinks]
  page = "/:slug/"

[[menu.main]]
  name = "Home"
  weight = -70
  identifier = "dphowes"
  url = "https://dphowes.github.io"
[[menu.main]]
  name = "Resume"
  weight = -70
  identifier = "resume"
  url = "/resume"

# Language Configuration
defaultContentLanguage = "en"

[languages]
  # edit this block for your own language
  [languages.en]
    lang = "en"
    languageName = "English"
    weight = 1
